// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_eigenMapMatMult
SEXP cpp_eigenMapMatMult(const Eigen::Map<Eigen::MatrixXd> A, Eigen::Map<Eigen::MatrixXd> B);
RcppExport SEXP _DAVINCHI_cpp_eigenMapMatMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_eigenMapMatMult(A, B));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rcpp_sylvester
arma::mat cpp_rcpp_sylvester(arma::mat left, arma::mat right, arma::mat total);
RcppExport SEXP _DAVINCHI_cpp_rcpp_sylvester(SEXP leftSEXP, SEXP rightSEXP, SEXP totalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type left(leftSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type right(rightSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type total(totalSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rcpp_sylvester(left, right, total));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rcpp_shur
Rcpp::List cpp_rcpp_shur(arma::mat x);
RcppExport SEXP _DAVINCHI_cpp_rcpp_shur(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rcpp_shur(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sylvester_pre
arma::mat cpp_sylvester_pre(arma::mat left, arma::mat Z2, arma::mat T2, arma::mat total);
RcppExport SEXP _DAVINCHI_cpp_sylvester_pre(SEXP leftSEXP, SEXP Z2SEXP, SEXP T2SEXP, SEXP totalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type left(leftSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z2(Z2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type total(totalSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sylvester_pre(left, Z2, T2, total));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DAVINCHI_cpp_eigenMapMatMult", (DL_FUNC) &_DAVINCHI_cpp_eigenMapMatMult, 2},
    {"_DAVINCHI_cpp_rcpp_sylvester", (DL_FUNC) &_DAVINCHI_cpp_rcpp_sylvester, 3},
    {"_DAVINCHI_cpp_rcpp_shur", (DL_FUNC) &_DAVINCHI_cpp_rcpp_shur, 1},
    {"_DAVINCHI_cpp_sylvester_pre", (DL_FUNC) &_DAVINCHI_cpp_sylvester_pre, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_DAVINCHI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
