# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_eigenMapMatMult <- function(A, B) {
    .Call('_DAVINCHI_cpp_eigenMapMatMult', PACKAGE = 'DAVINCHI', A, B)
}

cpp_rcpp_sylvester <- function(left, right, total) {
    .Call('_DAVINCHI_cpp_rcpp_sylvester', PACKAGE = 'DAVINCHI', left, right, total)
}

cpp_rcpp_shur <- function(x) {
    .Call('_DAVINCHI_cpp_rcpp_shur', PACKAGE = 'DAVINCHI', x)
}

cpp_sylvester_pre <- function(left, Z2, T2, total) {
    .Call('_DAVINCHI_cpp_sylvester_pre', PACKAGE = 'DAVINCHI', left, Z2, T2, total)
}

