# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Matrix multiplication
#' @param A 1st matrix
#' @param B 2nd matrix
#' @export
eigenMapMatMult <- function(A, B) {
    .Call(`_DAVINCHI_eigenMapMatMult`, A, B)
}

#' Schur decomposition
#' @param x input matrix
#' @export
rcpp_shur <- function(x) {
    .Call(`_DAVINCHI_rcpp_shur`, x)
}

#' Solve the sylvester equation
#' @param left
#' @param Z2
#' @param T2
#' @param total
#' @export
sylvester_pre <- function(left, Z2, T2, total) {
    .Call(`_DAVINCHI_sylvester_pre`, left, Z2, T2, total)
}

